name: Terraform CI for deploying Infrastructure


on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1  

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with: 
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init    

    - name: Executing workspace selection 
      run: terraform workspace select default

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan 

    - name: Terraform Apply
      run: terraform apply -auto-approve